describe('visit website', () => {
  it('passes', () => {
    cy.visit('http://localhost:3000/')
    cy.contains('Contact me here').click()
    cy.url().should('include','/#contact')
    cy.contains("About").click()
    cy.url().should('include','/#about')
    cy.contains("Projects").click()
    cy.url().should('include','/#project')
    cy.contains("Skills").click()
    cy.url().should('include','/#skills')
    cy.contains("Experience").click()
    cy.url().should('include','/#experience')
    cy.contains("Contact").click()
    cy.url().should('include','/#contact')
  })
})